/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Bagansio
 */
public class View_G extends javax.swing.JDialog {

    /**
     * Creates new form View_G
     */
    public View_G(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public View_G() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        b00 = new javax.swing.JLabel();
        b01 = new javax.swing.JLabel();
        b02 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b20 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        board = new javax.swing.JLabel();
        btn_restart = new javax.swing.JButton();
        txt_turn = new javax.swing.JLabel();
        label_winsO = new javax.swing.JLabel();
        label_winsX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(btn00, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, 150));
        getContentPane().add(btn01, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 160, 150));
        getContentPane().add(btn02, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 180, 150));
        getContentPane().add(btn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, 210));
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 170, 200));
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 190, 210));
        getContentPane().add(btn20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 190, 210));
        getContentPane().add(btn21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 170, 200));
        getContentPane().add(btn22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 190, 210));

        b00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b00, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, 150));

        b01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b01, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 160, 150));

        b02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b02, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 90, 160, 150));

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 180, 210));

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 160, 210));

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 180, 210));

        b20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 180, 180));

        b21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 160, 150));

        b22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/o.png"))); // NOI18N
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 180, 180));

        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/boardd.png"))); // NOI18N
        getContentPane().add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        btn_restart.setText("RESTART");
        getContentPane().add(btn_restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        txt_turn.setText("TURN OF: PLAYER 1 --X--");
        getContentPane().add(txt_turn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        label_winsO.setText("PLAYER 2 (O) WINS: 0");
        getContentPane().add(label_winsO, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        label_winsX.setText("PLAYER 1 (X) WINS: 0");
        getContentPane().add(label_winsX, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_G.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View_G dialog = new View_G(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel b00;
    public javax.swing.JLabel b01;
    public javax.swing.JLabel b02;
    public javax.swing.JLabel b10;
    public javax.swing.JLabel b11;
    public javax.swing.JLabel b12;
    public javax.swing.JLabel b20;
    public javax.swing.JLabel b21;
    public javax.swing.JLabel b22;
    private javax.swing.JLabel board;
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn_restart;
    private javax.swing.JLabel label_winsO;
    private javax.swing.JLabel label_winsX;
    private javax.swing.JLabel txt_turn;
    // End of variables declaration//GEN-END:variables
}
